/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2022-12-12 03:09:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp02_005felements;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;

public final class jsp09_005fparameters_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("	톰캣에서 get/post방식으로 전달되는 파라미터의 값을 읽어 올 때 사용하는\r\n");
      out.write("	문자셋은 기본적으로 utf-8로 전달된다. 그렇기 때문에 tomcat에서는 별도로\r\n");
      out.write("	문자셋을 설정하지 않아도 utf-8문자셋을 사용한다. 하지만 utf-8이 아닌\r\n");
      out.write("	문자셋을 파라미터로 전달하는 경우에는 server.xml의 <connector>태그의\r\n");
      out.write("	useBodyEncodingForURI=\"true\"를 추가하면 된다.\r\n");
      out.write("	\r\n");
      out.write("	true로 설정할 경우에는 get방식으로 전달되는 파라미터 값을 읽을 때 request\r\n");
      out.write("	객체의 getCharactorEncoding(\"utf-8\")메서드를 호출해서 지정된 문자셋을\r\n");
      out.write("	사용할 수 있게 한다.\r\n");
      out.write(" -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>요청된 파라미터의 정보 조회</h1>\r\n");
      out.write("	<h3>getParameter(String name)</h3>\r\n");
      out.write("	name 파라미터 : ");
      out.print( request.getParameter("name") );
      out.write("<br>\r\n");
      out.write("	pw   파라미터 : ");
      out.print( request.getParameter("pw") );
      out.write("<br>\r\n");
      out.write("	addr  파라미터 : ");
      out.print( request.getParameter("addr") );
      out.write("<br>\r\n");
      out.write("	hobby 파라미터 : ");
      out.print( request.getParameter("hobby") );
      out.write("<br>\r\n");
      out.write("	<hr />\r\n");
      out.write("	");

		String[] hobbies = request.getParameterValues("hobby");
		if(hobbies != null) {
			for(String hobby:hobbies) {
	
      out.write("\r\n");
      out.write("				취미 = ");
      out.print( hobby );
      out.write("<br>\r\n");
      out.write("	");

			}
		}
	
      out.write("\r\n");
      out.write("	<hr />\r\n");
      out.write("	\r\n");
      out.write("	<h3>getParameterMap()</h3>\r\n");
      out.write("	\r\n");
      out.write("	");

		Map<String, String[]> map = request.getParameterMap();
		String[] values = map.get("name");
		if(values != null) {
			for(int i=0;i<values.length;i++) {
	
      out.write("\r\n");
      out.write("				요청파라미터(name)의 값 = ");
      out.print( values[i] );
      out.write("<br>\r\n");
      out.write("	");

			}
		}
	
      out.write("\r\n");
      out.write("	<hr />\r\n");
      out.write("	\r\n");
      out.write("	");

		map = request.getParameterMap();
		values = map.get("hobby");
		if(values != null) {
			for(int i=0;i<values.length;i++) {
	
      out.write("\r\n");
      out.write("				요청파라미터(name)의 값 = ");
      out.print( values[i] );
      out.write("<br>\r\n");
      out.write("	");

			}
		}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
